### ISSUE TITLE
After conversion public key doesn't match private key

### ISSUE THREAD

**Issue by nazar-pc** [dchest/ed2curve-js#4]
Here are seed, Ed25519 keypair and X25519 keypair converted by this library:
```livescript
seed            = Buffer.from('9fc9b77445f8b077c29fe27fc581c52beb668ecd25f5bb2ba5777dee2a411e97', 'hex')
ed25519_public  = Buffer.from('8fbe438aab6c40dc2ebc839ba27530ca1bf23d4efd36958a3365406efe52ccd1', 'hex')
ed25519_private = Buffer.from('28e9e1d48cb0e52e437080e4a180058d7a42a07abcd05ea2ec4e6122cded8f6a0d2a6b9fd1878fd76ab20caecab666916ac3cc772fc57f8fa6e8dc3227bb8497', 'hex')
x25519_public   = Buffer.from('26100e941bdd2103038d8dec9a1884694736f591ee814e66ae6e2e2284757136', 'hex')
x25519_private  = Buffer.from('803fcdab44e9958d2f8e4d47b5f0d481d6ddb79dd462a18ee65cabe94a9e455c', 'hex')
```

Turns out, correct public key for `x25519_private` private key is `5b3e994f771a950c6ae29bb7f8ae0593c46d4a73312c15db3436b485468bbb6d`.

The code for mentioned outputs is fairly simple:
```livescript
seed = supercop.createSeed()
keys = supercop.createKeyPair(seed)
{
    'seed'    : seed
    'ed25519' :
        'public'  : keys.publicKey
        'private' : keys.secretKey
    'x25519'  :
        'public'  : ed2curve.convertPublicKey(keys.publicKey)
        'private' : ed2curve.convertSecretKey(keys.secretKey)
}
```

So it seems that conversion is done incorrectly: either public key or private key or both are incorrect.

@CodesInChaos, @nightcracker, maybe you can clarify what is wrong here?

**Comment by dchest** [comment]
How did you get this ed25519 private key?

```
> var kp1 = nacl.sign.keyPair.fromSeed(Buffer.from('9fc9b77445f8b077c29fe27fc581c52beb668ecd25f5bb2ba5777dee2a411e97', 'hex'))
> Buffer.from(kp1.publicKey).toString('hex')
'8fbe438aab6c40dc2ebc839ba27530ca1bf23d4efd36958a3365406efe52ccd1'
> Buffer.from(kp1.secretKey).toString('hex')
'9fc9b77445f8b077c29fe27fc581c52beb668ecd25f5bb2ba5777dee2a411e978fbe438aab6c40dc2ebc839ba27530ca1bf23d4efd36958a3365406efe52ccd1'
```

^^ doesn't match yours.

Your ed25519_private doesn't produce the public key that you provided:

```
> var kp2 = nacl.sign.keyPair.fromSecretKey(Buffer.from(ed25519_private, 'hex'))
undefined
> Buffer.from(kp2.publicKey).toString('hex')
'0d2a6b9fd1878fd76ab20caecab666916ac3cc772fc57f8fa6e8dc3227bb8497'
```

The correct private key, though, produces the correct X25519 public and private keys when converted.

```
> var dkp1 = ed2curve.convertKeyPair(kp1)
undefined
> Buffer.from(dkp1.publicKey).toString('hex')
'26100e941bdd2103038d8dec9a1884694736f591ee814e66ae6e2e2284757136'
> Buffer.from(dkp1.secretKey).toString('hex')
'28e9e1d48cb0e52e437080e4a180058d7a42a07abcd05ea2ec4e6122cded8f6a'
> Buffer.from(nacl.scalarMult.base(dkp1.secretKey)).toString('hex')
'26100e941bdd2103038d8dec9a1884694736f591ee814e66ae6e2e2284757136'
```

**Comment by nazar-pc** [comment]
I've got both public and private keys from the same seed using https://github.com/nazar-pc/supercop.wasm, which in turn is WebAssembly version of https://github.com/orlp/ed25519.

There are tests for signing and verification and they are good: https://github.com/nazar-pc/supercop.wasm/blob/master/test/index.js

Mentioned tests use different keypair, but the same happens with either one. Also I've compiled a piece of libsodium to WebAssembly/JavaScript (https://github.com/nazar-pc/ed25519-to-x25519.wasm) and it produces the same result as this library, which is very interesting.

@orlp, maybe you have an idea what is wrong here?

**Comment by dchest** [comment]
Oh, I see. It looks like orlp/ed25519 uses a different format of secret keys: the secret key storead as already hashed: https://github.com/orlp/ed25519/blob/master/src/keypair.c#L6

while TweetNacl hashes it during singing or during generating public key:
https://github.com/dchest/tweetnacl-js/blob/master/nacl.js#L762
https://github.com/dchest/tweetnacl-js/blob/master/nacl.js#L710

**Comment by nazar-pc** [comment]
Wow, hashing means I'll not be able to extract private key anymore.
There are no more questions to this library, thanks for your help!

**Comment by dchest** [comment]
You're welcome! Well, the actual private key is the hash of random bytes, it's just that the standard format of Ed25519 is to do this hashing when signing or generating public key, and if you want to use it for X25519, just avoid this hash here: https://github.com/dchest/ed2curve-js/blob/master/ed2curve.js#L227

As an optimization, if you control private key (e.g. signing software updates), storing hash and directly using it when signing or generating public key is fine, but of course, it makes the library incompatible with other implementations, and allows some attacks if you don't control the private key.

**Comment by nazar-pc** [comment]
Yes, I've resolved the issue by using seed directly as private key on input without any hashing, since I have access to seed. It seems to work fine this way.
